        ; mpl115a2
        ;  functions
        EXTERN      InitMpl115a2
        EXTERN      PowerMpl115a2
        EXTERN      ShutdownMpl115a2

        EXTERN      SingleSamplePressure
        EXTERN      SamplePressure

        EXTERN      CalcAltitude
        EXTERN      CalculatePressure
        EXTERN      CalculateTemperature

        ;  variables
        EXTERN      pressureH
        EXTERN      pressureL
        EXTERN      altitudeMeterH
        EXTERN      altitudeMeterL
